apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      containers:
      - name: backstage
        image: 851725646489.dkr.ecr.us-east-1.amazonaws.com/backstage:main-1963378
        ports:
        - name: http
          containerPort: 7007
        env:
        - name: NODE_ENV
          value: production
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: '5432'
        - name: K8S_CLUSTER_URL
          value: https://kubernetes.default.svc
        - name: K8S_CLUSTER_NAME
          value: poc-kafka 
        envFrom:
        - secretRef:
            name: postgres-secrets
        - secretRef:
            name: backstage-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      initContainers:
      - name: wait-for-postgres
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h postgres -p 5432 -U backstage; do
            echo "Waiting for postgres..."
            sleep 2
          done
